<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130301152304 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Reminder (id INT AUTO_INCREMENT NOT NULL, rfid_id VARCHAR(16) DEFAULT NULL, arrivalDate DATETIME NOT NULL, leeway INT NOT NULL, UNIQUE INDEX UNIQ_B9412D1681509B71 (rfid_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE RFID (id VARCHAR(16) NOT NULL, type VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Reminder ADD CONSTRAINT FK_B9412D1681509B71 FOREIGN KEY (rfid_id) REFERENCES RFID (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Reminder DROP FOREIGN KEY FK_B9412D1681509B71");
        $this->addSql("DROP TABLE Reminder");
        $this->addSql("DROP TABLE RFID");
    }
}
